import { useState, useEffect } from "react";
import twColors from "tailwindcss/colors";

const ColorBlock = ({ color, selectedColor, ...props }) => {
  const [cl, setCl] = useState(`bg-${props.key}`); //class of block
  const [hex, setHex] = useState(twColors[props.key]); //hex val of block
  const bg = props.key; //color name

  const handleClick = (e) => {
    props.onClick(color, hex);
  };

  //when selected color changes update className
  useEffect(() => {
    if (selectedColor === color) {
      setCl(`bg-${bg} border-2 border-blue-500`);
      setHex(twColors[props.key]);
    } else {
      setCl(`bg-${bg}`);
    }
  }, [bg, color, selectedColor, props.key]);

  return <span id={color} className={cl} onClick={handleClick}></span>;
};

const ColorPicker = ({ visible, ...props }) => {
  const [selectedColor, setSelectedColor] = useState(""); //used to highlight
  const [hex, setHex] = useState("");
  const [cl, setCl] = useState("hidden");

  useEffect(() => {
    if (visible === true) {
      setCl(
        "p-3 w-1/2 absolute visible top-0 right-0 bg-white border-1 border-slate-900 shadow-left"
      );
    } else {
      setCl("hidden");
    }
  }, [visible]);

  const handleSelected = (e, hex) => {
    setSelectedColor(props.key);
    setHex(hex);
    props.onSelect(props.key, hex); //send to parent
  };

  const styles = {
    top: "text-xs text-center",
    left: "text-xl text-right",
  };

  // Default colors -->
  // white, black, rose, green, blue, orange, yellow, purple, lime, emerald, teal, cyan, indigo, violet, fuchsia, pink, rose, sky, gray, slate, neutral, neutral, stone, amber,  -->
  return (
    <div className={cl}>
      <div className="text-xs font-bold text-center mb-2 ">
        Tailwind Default Colors
      </div>

      <div className="w-full mx-auto grid grid-cols-11 gap-1 ">
        <div className="text-xs text-right"></div>
        <div className={styles.top}>50</div>
        <div className={styles.top}>100</div>
        <div className={styles.top}>200</div>
        <div className={styles.top}>300</div>
        <div className={styles.top}>400</div>
        <div className={styles.top}>500</div>
        <div className={styles.top}>600</div>
        <div className={styles.top}>700</div>
        <div className={styles.top}>800</div>
        <div className={styles.top}>900</div>

        <div className="text-xs text-right">red</div>
        <ColorBlock
          key="red-50"
          color="bg-red-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-100"
          color="bg-red-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-200"
          color="bg-red-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-300"
          color="bg-red-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-400"
          color="bg-red-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-500"
          color="bg-red-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-600"
          color="bg-red-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-700"
          color="bg-red-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-800"
          color="bg-red-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="red-900"
          color="bg-red-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">rose</div>
        <ColorBlock
          key="rose-50"
          color="bg-rose-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-100"
          color="bg-rose-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-200"
          color="bg-rose-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-300"
          color="bg-rose-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-400"
          color="bg-rose-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-500"
          color="bg-rose-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-600"
          color="bg-rose-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-700"
          color="bg-rose-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-800"
          color="bg-rose-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="rose-900"
          color="bg-rose-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">pink</div>
        <ColorBlock
          key="pink-50"
          color="bg-pink-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-100"
          color="bg-pink-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-200"
          color="bg-pink-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-300"
          color="bg-pink-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-400"
          color="bg-pink-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-500"
          color="bg-pink-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-600"
          color="bg-pink-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-700"
          color="bg-pink-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-800"
          color="bg-pink-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="pink-900"
          color="bg-pink-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">fuchsia</div>
        <ColorBlock
          key="fuchsia-50"
          color="bg-fuchsia-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-100"
          color="bg-fuchsia-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-200"
          color="bg-fuchsia-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-300"
          color="bg-fuchsia-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-400"
          color="bg-fuchsia-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-500"
          color="bg-fuchsia-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-600"
          color="bg-fuchsia-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-700"
          color="bg-fuchsia-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-800"
          color="bg-fuchsia-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="fuchsia-900"
          color="bg-fuchsia-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <div className="text-xs text-right">purple</div>
        <ColorBlock
          key="purple-50"
          color="bg-purple-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-100"
          color="bg-purple-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-200"
          color="bg-purple-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-300"
          color="bg-purple-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-400"
          color="bg-purple-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-500"
          color="bg-purple-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-600"
          color="bg-purple-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-700"
          color="bg-purple-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-800"
          color="bg-purple-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="purple-900"
          color="bg-purple-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">violet</div>
        <ColorBlock
          key="violet-50"
          color="bg-violet-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-100"
          color="bg-violet-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-200"
          color="bg-violet-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-300"
          color="bg-violet-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-400"
          color="bg-violet-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-500"
          color="bg-violet-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-600"
          color="bg-violet-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-700"
          color="bg-violet-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-800"
          color="bg-violet-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="violet-900"
          color="bg-violet-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">indigo</div>
        <ColorBlock
          key="indigo-50"
          color="bg-indigo-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-100"
          color="bg-indigo-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-200"
          color="bg-indigo-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-300"
          color="bg-indigo-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-400"
          color="bg-indigo-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-500"
          color="bg-indigo-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-600"
          color="bg-indigo-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-700"
          color="bg-indigo-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-800"
          color="bg-indigo-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="indigo-900"
          color="bg-indigo-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">blue</div>
        <ColorBlock
          key="blue-50"
          color="bg-blue-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-100"
          color="bg-blue-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-200"
          color="bg-blue-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-300"
          color="bg-blue-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-400"
          color="bg-blue-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-500"
          color="bg-blue-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-600"
          color="bg-blue-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-700"
          color="bg-blue-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-800"
          color="bg-blue-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="blue-900"
          color="bg-blue-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">sky</div>
        <ColorBlock
          key="sky-50"
          color="bg-sky-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-100"
          color="bg-sky-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-200"
          color="bg-sky-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-300"
          color="bg-sky-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-400"
          color="bg-sky-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-500"
          color="bg-sky-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-600"
          color="bg-sky-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-700"
          color="bg-sky-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-800"
          color="bg-sky-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="sky-900"
          color="bg-sky-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">cyan</div>
        <ColorBlock
          key="cyan-50"
          color="bg-cyan-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-100"
          color="bg-cyan-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-200"
          color="bg-cyan-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-300"
          color="bg-cyan-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-400"
          color="bg-cyan-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-500"
          color="bg-cyan-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-600"
          color="bg-cyan-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-700"
          color="bg-cyan-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-800"
          color="bg-cyan-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="cyan-900"
          color="bg-cyan-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">teal</div>
        <ColorBlock
          key="teal-50"
          color="bg-teal-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-100"
          color="bg-teal-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-200"
          color="bg-teal-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-300"
          color="bg-teal-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-400"
          color="bg-teal-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-500"
          color="bg-teal-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-600"
          color="bg-teal-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-700"
          color="bg-teal-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-800"
          color="bg-teal-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="teal-900"
          color="bg-teal-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">emerald</div>
        <ColorBlock
          key="emerald-50"
          color="bg-emerald-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-100"
          color="bg-emerald-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-200"
          color="bg-emerald-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-300"
          color="bg-emerald-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-400"
          color="bg-emerald-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-500"
          color="bg-emerald-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-600"
          color="bg-emerald-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-700"
          color="bg-emerald-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-800"
          color="bg-emerald-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="emerald-900"
          color="bg-emerald-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">green</div>
        <ColorBlock
          key="green-50"
          color="bg-green-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-100"
          color="bg-green-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-200"
          color="bg-green-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-300"
          color="bg-green-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-400"
          color="bg-green-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-500"
          color="bg-green-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-600"
          color="bg-green-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-700"
          color="bg-green-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-800"
          color="bg-green-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="green-900"
          color="bg-green-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">lime</div>
        <ColorBlock
          key="lime-50"
          color="bg-lime-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-100"
          color="bg-lime-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-200"
          color="bg-lime-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-300"
          color="bg-lime-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-400"
          color="bg-lime-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-500"
          color="bg-lime-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-600"
          color="bg-lime-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-700"
          color="bg-lime-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-800"
          color="bg-lime-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="lime-900"
          color="bg-lime-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">yellow</div>
        <ColorBlock
          key="yellow-50"
          color="bg-yellow-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-100"
          color="bg-yellow-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-200"
          color="bg-yellow-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-300"
          color="bg-yellow-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-400"
          color="bg-yellow-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-500"
          color="bg-yellow-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-600"
          color="bg-yellow-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-700"
          color="bg-yellow-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-800"
          color="bg-yellow-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="yellow-900"
          color="bg-yellow-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">amber</div>
        <ColorBlock
          key="amber-50"
          color="bg-amber-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-100"
          color="bg-amber-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-200"
          color="bg-amber-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-300"
          color="bg-amber-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-400"
          color="bg-amber-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-500"
          color="bg-amber-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-600"
          color="bg-amber-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-700"
          color="bg-amber-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-800"
          color="bg-amber-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="amber-900"
          color="bg-amber-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">orange</div>
        <ColorBlock
          key="orange-50"
          color="bg-orange-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-100"
          color="bg-orange-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-200"
          color="bg-orange-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-300"
          color="bg-orange-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-400"
          color="bg-orange-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-500"
          color="bg-orange-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-600"
          color="bg-orange-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-700"
          color="bg-orange-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-800"
          color="bg-orange-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="orange-900"
          color="bg-orange-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">stone</div>
        <ColorBlock
          key="stone-50"
          color="bg-stone-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-100"
          color="bg-stone-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-200"
          color="bg-stone-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-300"
          color="bg-stone-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-400"
          color="bg-stone-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-500"
          color="bg-stone-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-600"
          color="bg-stone-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-700"
          color="bg-stone-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-800"
          color="bg-stone-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="stone-900"
          color="bg-stone-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">neutral</div>

        <ColorBlock
          key="neutral-50"
          color="bg-neutral-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-100"
          color="bg-neutral-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-200"
          color="bg-neutral-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-300"
          color="bg-neutral-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-400"
          color="bg-neutral-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-500"
          color="bg-neutral-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-600"
          color="bg-neutral-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-700"
          color="bg-neutral-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-800"
          color="bg-neutral-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="neutral-900"
          color="bg-neutral-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">zinc</div>
        <ColorBlock
          key="zinc-50"
          color="bg-zinc-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-100"
          color="bg-zinc-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-200"
          color="bg-zinc-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-300"
          color="bg-zinc-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-400"
          color="bg-zinc-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-500"
          color="bg-zinc-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-600"
          color="bg-zinc-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-700"
          color="bg-zinc-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-800"
          color="bg-zinc-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="zinc-900"
          color="bg-zinc-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">gray</div>
        <ColorBlock
          key="gray-50"
          color="bg-gray-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-100"
          color="bg-gray-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-200"
          color="bg-gray-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-300"
          color="bg-gray-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-400"
          color="bg-gray-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-500"
          color="bg-gray-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-600"
          color="bg-gray-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-700"
          color="bg-gray-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-800"
          color="bg-gray-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="gray-900"
          color="bg-gray-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right">slate</div>
        <ColorBlock
          key="slate-50"
          color="bg-slate-50"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-100"
          color="bg-slate-100"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-200"
          color="bg-slate-200"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-300"
          color="bg-slate-300"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-400"
          color="bg-slate-400"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-500"
          color="bg-slate-500"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-600"
          color="bg-slate-600"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-700"
          color="bg-slate-700"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-800"
          color="bg-slate-800"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>
        <ColorBlock
          key="slate-900"
          color="bg-slate-900"
          onClick={handleSelected}
          selectedColor={selectedColor}
        ></ColorBlock>

        <div className="text-xs text-right"></div>
        <div className={styles.top}>50</div>
        <div className={styles.top}>100</div>
        <div className={styles.top}>200</div>
        <div className={styles.top}>300</div>
        <div className={styles.top}>400</div>
        <div className={styles.top}>500</div>
        <div className={styles.top}>600</div>
        <div className={styles.top}>700</div>
        <div className={styles.top}>800</div>
        <div className={styles.top}>900</div>
      </div>
    </div>
  );
};

export default ColorPicker;

const safelist = `text-red-50 
                  text-red-100 
                  text-red-200
                  text-red-300
                  text-red-400
                  text-red-500
                  text-red-600
                  text-red-700
                  text-red-800
                  text-red-900

                  text-rose-50 
                  text-rose-100 
                  text-rose-200
                  text-rose-300
                  text-rose-400
                  text-rose-500
                  text-rose-600
                  text-rose-700
                  text-rose-800
                  text-rose-900

                  text-pink-50 
                  text-pink-100 
                  text-pink-200
                  text-pink-300
                  text-pink-400
                  text-pink-500
                  text-pink-600
                  text-pink-700
                  text-pink-800
                  text-pink-900

                  text-fuchsia-50 
                  text-fuchsia-100 
                  text-fuchsia-200
                  text-fuchsia-300
                  text-fuchsia-400
                  text-fuchsia-500
                  text-fuchsia-600
                  text-fuchsia-700
                  text-fuchsia-800
                  text-fuchsia-900


                  text-purple-50 
                  text-purple-100 
                  text-purple-200
                  text-purple-300
                  text-purple-400
                  text-purple-500
                  text-purple-600
                  text-purple-700
                  text-purple-800
                  text-purple-900

                  text-violet-50 
                  text-violet-100 
                  text-violet-200
                  text-violet-300
                  text-violet-400
                  text-violet-500
                  text-violet-600
                  text-violet-700
                  text-violet-800
                  text-violet-900

                  text-indigo-50 
                  text-indigo-100 
                  text-indigo-200
                  text-indigo-300
                  text-indigo-400
                  text-indigo-500
                  text-indigo-600
                  text-indigo-700
                  text-indigo-800
                  text-indigo-900

                  text-blue-50 
                  text-blue-100 
                  text-blue-200
                  text-blue-300
                  text-blue-400
                  text-blue-500
                  text-blue-600
                  text-blue-700
                  text-blue-800
                  text-blue-900

                  text-sky-50 
                  text-sky-100 
                  text-sky-200
                  text-sky-300
                  text-sky-400
                  text-sky-500
                  text-sky-600
                  text-sky-700
                  text-sky-800
                  text-sky-900

                  text-cyan-50 
                  text-cyan-100 
                  text-cyan-200
                  text-cyan-300
                  text-cyan-400
                  text-cyan-500
                  text-cyan-600
                  text-cyan-700
                  text-cyan-800
                  text-cyan-900

                  text-teal-50 
                  text-teal-100 
                  text-teal-200
                  text-teal-300
                  text-teal-400
                  text-teal-500
                  text-teal-600
                  text-teal-700
                  text-teal-800
                  text-teal-900

                  text-emerald-50 
                  text-emerald-100 
                  text-emerald-200
                  text-emerald-300
                  text-emerald-400
                  text-emerald-500
                  text-emerald-600
                  text-emerald-700
                  text-emerald-800
                  text-emerald-900

                  text-green-50 
                  text-green-100 
                  text-green-200
                  text-green-300
                  text-green-400
                  text-green-500
                  text-green-600
                  text-green-700
                  text-green-800
                  text-green-900

                  text-lime-50 
                  text-lime-100 
                  text-lime-200
                  text-lime-300
                  text-lime-400
                  text-lime-500
                  text-lime-600
                  text-lime-700
                  text-lime-800
                  text-lime-900

                  text-yellow-50 
                  text-yellow-100 
                  text-yellow-200
                  text-yellow-300
                  text-yellow-400
                  text-yellow-500
                  text-yellow-600
                  text-yellow-700
                  text-yellow-800
                  text-yellow-900

                  text-amber-50 
                  text-amber-100 
                  text-amber-200
                  text-amber-300
                  text-amber-400
                  text-amber-500
                  text-amber-600
                  text-amber-700
                  text-amber-800
                  text-amber-900

                  text-orange-50 
                  text-orange-100 
                  text-orange-200
                  text-orange-300
                  text-orange-400
                  text-orange-500
                  text-orange-600
                  text-orange-700
                  text-orange-800
                  text-orange-900

                  text-stone-50 
                  text-stone-100 
                  text-stone-200
                  text-stone-300
                  text-stone-400
                  text-stone-500
                  text-stone-600
                  text-stone-700
                  text-stone-800
                  text-stone-900

                  text-neutral-50 
                  text-neutral-100 
                  text-neutral-200
                  text-neutral-300
                  text-neutral-400
                  text-neutral-500
                  text-neutral-600
                  text-neutral-700
                  text-neutral-800
                  text-neutral-900

                  text-zinc-50 
                  text-zinc-100 
                  text-zinc-200
                  text-zinc-300
                  text-zinc-400
                  text-zinc-500
                  text-zinc-600
                  text-zinc-700
                  text-zinc-800
                  text-zinc-900


                  text-gray-50 
                  text-gray-100 
                  text-gray-200
                  text-gray-300
                  text-gray-400
                  text-gray-500
                  text-gray-600
                  text-gray-700
                  text-gray-800
                  text-gray-900


                  text-slate-50 
                  text-slate-100 
                  text-slate-200
                  text-slate-300
                  text-slate-400
                  text-slate-500
                  text-slate-600
                  text-slate-700
                  text-slate-800
                  text-slate-900
                  `;
